import type { DocsNavItem } from "./docsNav";

// Generated by scripts/migrate-officialcto.mjs from the current OfficialCTO working tree.
export const officialCtoInterviewNav: DocsNavItem[] = [
  {
    "title": "Algorithms and Data Structures",
    "href": "/interview/algorithms/v1",
    "children": [
      {
        "title": "Advanced String Algorithms",
        "href": "/interview/algorithms/v1/advanced-string-algorithms"
      },
      {
        "title": "Trees - Traversals and Balancing",
        "href": "/interview/algorithms/v1/binary-trees-traversals-balancing"
      },
      {
        "title": "Capstone - Mixing Patterns in Real Interviews",
        "href": "/interview/algorithms/v1/capstone-mixing-patterns"
      },
      {
        "title": "1D Dynamic Programming",
        "href": "/interview/algorithms/v1/dynamic-programming-1d-patterns"
      },
      {
        "title": "2D/Multi-DP Patterns",
        "href": "/interview/algorithms/v1/dynamic-programming-2d-patterns"
      },
      {
        "title": "Graphs - Shortest Paths and Topological Sort",
        "href": "/interview/algorithms/v1/graphs-shortest-paths-topological-sort"
      },
      {
        "title": "Greedy and Bit Manipulation Tricks",
        "href": "/interview/algorithms/v1/greedy-bit-manipulation"
      },
      {
        "title": "Heaps - Priority Queue Patterns",
        "href": "/interview/algorithms/v1/heaps-priority-queues"
      },
      {
        "title": "Linked Lists - Reversal and Cycle Detection",
        "href": "/interview/algorithms/v1/linked-lists-reversal-cycle-detection"
      },
      {
        "title": "Prefix Sums and Hashing",
        "href": "/interview/algorithms/v1/prefix-sums-hashing"
      },
      {
        "title": "Introduction to Problem-Solving Mindsets",
        "href": "/interview/algorithms/v1/problem-solving-mindsets"
      },
      {
        "title": "Segment and Fenwick Trees",
        "href": "/interview/algorithms/v1/segment-fenwick-trees"
      },
      {
        "title": "Stacks and Queues - BFS/DFS",
        "href": "/interview/algorithms/v1/stacks-queues-bfs-dfs"
      },
      {
        "title": "Two-Pointers and Sliding Windows",
        "href": "/interview/algorithms/v1/two-pointers-sliding-windows"
      },
      {
        "title": "Union-Find and Optimizations",
        "href": "/interview/algorithms/v1/union-find-optimizations"
      }
    ]
  },
  {
    "title": "Architectural Design Patterns",
    "href": "/interview/architectural-design-patterns/v1",
    "children": [
      {
        "title": "API Gateway & Backend for Frontend (BFF) Pattern",
        "href": "/interview/architectural-design-patterns/v1/api-gateway-bff"
      },
      {
        "title": "Circuit Breaker Pattern",
        "href": "/interview/architectural-design-patterns/v1/circuit-breaker"
      },
      {
        "title": "CQRS (Command Query Responsibility Segregation) Pattern",
        "href": "/interview/architectural-design-patterns/v1/cqrs-pattern"
      },
      {
        "title": "Database per Service Pattern",
        "href": "/interview/architectural-design-patterns/v1/database-per-service"
      },
      {
        "title": "Event-Driven Architecture Pattern",
        "href": "/interview/architectural-design-patterns/v1/event-driven-architecture"
      },
      {
        "title": "Event Sourcing Pattern",
        "href": "/interview/architectural-design-patterns/v1/event-sourcing-pattern"
      },
      {
        "title": "Hexagonal Architecture Pattern (Ports & Adapters)",
        "href": "/interview/architectural-design-patterns/v1/hexagonal-architecture"
      },
      {
        "title": "Layered Architecture Pattern",
        "href": "/interview/architectural-design-patterns/v1/layered-architecture"
      },
      {
        "title": "Microservices vs Modular Monolith",
        "href": "/interview/architectural-design-patterns/v1/microservices-vs-monolith"
      },
      {
        "title": "Onion Architecture Pattern",
        "href": "/interview/architectural-design-patterns/v1/onion-architecture"
      },
      {
        "title": "Saga Pattern",
        "href": "/interview/architectural-design-patterns/v1/saga-pattern"
      },
      {
        "title": "Strangler Fig Pattern",
        "href": "/interview/architectural-design-patterns/v1/strangler-fig"
      }
    ]
  },
  {
    "title": "Architectural Design Principles",
    "href": "/interview/architectural-design-principles/v1",
    "children": [
      {
        "title": "Architectural Trade-offs",
        "href": "/interview/architectural-design-principles/v1/architectural-tradeoffs"
      },
      {
        "title": "Information Hiding in Architecture",
        "href": "/interview/architectural-design-principles/v1/architecture-info-hiding"
      },
      {
        "title": "Component Cohesion Principles (REP, CCP, CRP)",
        "href": "/interview/architectural-design-principles/v1/component-cohesion"
      },
      {
        "title": "Component Coupling Principles (ADP, SDP, SAP)",
        "href": "/interview/architectural-design-principles/v1/component-coupling"
      },
      {
        "title": "Domain-Driven Design Principles (DDD Lite)",
        "href": "/interview/architectural-design-principles/v1/ddd-principles"
      },
      {
        "title": "Dependency Rule (Clean Architecture)",
        "href": "/interview/architectural-design-principles/v1/dependency-rule"
      },
      {
        "title": "Evolutionary Architecture Principles",
        "href": "/interview/architectural-design-principles/v1/evolutionary-architecture"
      },
      {
        "title": "Introduction to Architectural Design Principles & Patterns",
        "href": "/interview/architectural-design-principles/v1/intro"
      },
      {
        "title": "Principle of Least Knowledge at Service Boundaries",
        "href": "/interview/architectural-design-principles/v1/least-knowledge-services"
      },
      {
        "title": "Observability Principles",
        "href": "/interview/architectural-design-principles/v1/observability"
      },
      {
        "title": "Performance & Caching Principles",
        "href": "/interview/architectural-design-principles/v1/performance-caching"
      },
      {
        "title": "Resilience & Fault Tolerance Principles",
        "href": "/interview/architectural-design-principles/v1/resilience-fault-tolerance"
      },
      {
        "title": "Scalability & Availability Principles",
        "href": "/interview/architectural-design-principles/v1/scalability-availability"
      },
      {
        "title": "Security Principles in Architecture",
        "href": "/interview/architectural-design-principles/v1/security-principles"
      },
      {
        "title": "System-Level Cohesion & Coupling",
        "href": "/interview/architectural-design-principles/v1/system-cohesion-coupling"
      }
    ]
  },
  {
    "title": "Behavioral & Leadership Interview Preparation",
    "href": "/interview/behavioral/v1",
    "children": [
      {
        "title": "Tailoring for Amazon - Leadership Principles",
        "href": "/interview/behavioral/v1/amazon-principles"
      },
      {
        "title": "Capstone - Full Mock Behavioral Interview",
        "href": "/interview/behavioral/v1/capstone-interview"
      },
      {
        "title": "Common Questions & Conflict Frameworks",
        "href": "/interview/behavioral/v1/common-questions"
      },
      {
        "title": "Effective Communication in Technical Settings",
        "href": "/interview/behavioral/v1/communication"
      },
      {
        "title": "Conflict Resolution & Handling Failures",
        "href": "/interview/behavioral/v1/conflict-failure"
      },
      {
        "title": "Tailoring for Google - GCA and Googleyness",
        "href": "/interview/behavioral/v1/google-gca"
      },
      {
        "title": "Influencing & Managing Up/Down",
        "href": "/interview/behavioral/v1/influencing-managing"
      },
      {
        "title": "Introduction to Behavioral Interviews & STAR Framework",
        "href": "/interview/behavioral/v1/intro-behavioral"
      },
      {
        "title": "Leadership - Leading Teams",
        "href": "/interview/behavioral/v1/leadership"
      },
      {
        "title": "Learning, Growth, and Continuous Improvement",
        "href": "/interview/behavioral/v1/learning-growth"
      },
      {
        "title": "Tailoring for Meta - Execution Speed & Real-Time Systems",
        "href": "/interview/behavioral/v1/meta-execution"
      },
      {
        "title": "Tailoring for Netflix - Freedom & Responsibility",
        "href": "/interview/behavioral/v1/netflix-responsibility"
      },
      {
        "title": "Ownership and Innovation",
        "href": "/interview/behavioral/v1/ownership-innovation"
      },
      {
        "title": "Problem-Solving and Technical Trade-Offs",
        "href": "/interview/behavioral/v1/problem-solving"
      },
      {
        "title": "Teamwork and Collaboration",
        "href": "/interview/behavioral/v1/teamwork"
      }
    ]
  },
  {
    "title": "Writing Clean Code",
    "href": "/interview/clean-code/v1",
    "children": [
      {
        "title": "Documentation and Code Reviews",
        "href": "/interview/clean-code/v1/documentation-reviews"
      },
      {
        "title": "Robust Error Handling",
        "href": "/interview/clean-code/v1/error-handling"
      },
      {
        "title": "Introduction to Clean Code - Principles and Impact",
        "href": "/interview/clean-code/v1/intro-clean-code"
      },
      {
        "title": "Designing Modular Code",
        "href": "/interview/clean-code/v1/modular-code"
      },
      {
        "title": "Balancing Performance and Clarity",
        "href": "/interview/clean-code/v1/performance-clarity"
      },
      {
        "title": "Crafting Readable Code",
        "href": "/interview/clean-code/v1/readable-code"
      },
      {
        "title": "Writing Testable Code",
        "href": "/interview/clean-code/v1/testable-code"
      }
    ]
  },
  {
    "title": "Database Series Hub",
    "href": "/interview/database/v1",
    "children": [
      {
        "title": "Caching & Query Optimization (Advanced Database Internals Edition)",
        "href": "/interview/database/v1/caching-and-query-optimization"
      },
      {
        "title": "CAP Theorem & Consistency Models",
        "href": "/interview/database/v1/cap-theorem"
      },
      {
        "title": "Database Case Studies",
        "href": "/interview/database/v1/case-studies"
      },
      {
        "title": "Distributed Transactions & Patterns (Database Internals Edition)",
        "href": "/interview/database/v1/distributed-transactions"
      },
      {
        "title": "Database Fundamentals (Moderately Expanded Edition)",
        "href": "/interview/database/v1/fundamentals"
      },
      {
        "title": "Database Indexing Internals: The Complete Guide",
        "href": "/interview/database/v1/indexing"
      },
      {
        "title": "Interview Guide: Databases in High-Level Design (HLD)",
        "href": "/interview/database/v1/interview-guide"
      },
      {
        "title": "Polyglot Persistence & System Design Patterns — Deep Internals, Use Cases, and Interview Frameworks",
        "href": "/interview/database/v1/polyglot-persistence"
      },
      {
        "title": "Database Scaling Patterns — Deep Internals, Trade-Offs & System Design Guidance",
        "href": "/interview/database/v1/scaling-patterns"
      },
      {
        "title": "Sharding vs Replication vs Partitioning — Deep Internals, Trade-Offs & System Design Interview Guide",
        "href": "/interview/database/v1/sharding-vs-replication-vs-partitioning"
      },
      {
        "title": "Specialized Databases: Internals, Trade-Offs & How to Choose the Right One in System Design Interviews",
        "href": "/interview/database/v1/specialized-databases"
      },
      {
        "title": "SQL vs NoSQL — Internal Architecture, Access Patterns & When to Use Each",
        "href": "/interview/database/v1/sql-vs-nosql"
      },
      {
        "title": "Internals",
        "href": "/interview/database/v1/internals",
        "children": [
          {
            "title": "2. B+ Trees: The OLTP Workhorse",
            "href": "/interview/database/v1/internals/b-plus-trees"
          },
          {
            "title": "11. Architecture of Bigtable, Cassandra & DynamoDB",
            "href": "/interview/database/v1/internals/big-database-archittecture"
          },
          {
            "title": "7. Buffer Pools, Caches & Page Replacement",
            "href": "/interview/database/v1/internals/buffer-pool-cache-page-replacement"
          },
          {
            "title": "12. Build Your Own Storage Engine (Capstone)",
            "href": "/interview/database/v1/internals/build-own-db"
          },
          {
            "title": "5. Compaction: The Hidden Cost Behind LSM Engines",
            "href": "/interview/database/v1/internals/compaction"
          },
          {
            "title": "Distributed Coordination Internals: Consensus, Gossip, Replication & Failure Handling",
            "href": "/interview/database/v1/internals/distributed-coordination"
          },
          {
            "title": "10. Distributed Storage: Replication, Consistency & Quorums",
            "href": "/interview/database/v1/internals/distributed-storage"
          },
          {
            "title": "0. Introduction",
            "href": "/interview/database/v1/internals/introduction"
          },
          {
            "title": "3. LSM Trees: The Write-Optimized Revolution",
            "href": "/interview/database/v1/internals/lsm-trees"
          },
          {
            "title": "Advanced Database Internals: The Missing Pieces",
            "href": "/interview/database/v1/internals/missing-pieces"
          },
          {
            "title": "6. MVCC: High-Concurrency Reads & Writes Without Locks",
            "href": "/interview/database/v1/internals/mvcc"
          },
          {
            "title": "9. Parquet, ORC & Columnar Storage Internals",
            "href": "/interview/database/v1/internals/parquet-columnar-internals"
          },
          {
            "title": "8. Query Execution: What Really Happens During SELECT",
            "href": "/interview/database/v1/internals/query-execution"
          },
          {
            "title": "4. SSTables: Immutable Storage for Scale",
            "href": "/interview/database/v1/internals/sstables"
          },
          {
            "title": "1. Write-Ahead Logs & Durable Write Paths",
            "href": "/interview/database/v1/internals/write-ahead-logs"
          }
        ]
      }
    ]
  },
  {
    "title": "Design Patterns",
    "href": "/interview/design-patterns/v1",
    "children": [
      {
        "title": "Abstract Factory Pattern in Java – Building a Thematic Home Decorator",
        "href": "/interview/design-patterns/v1/abstract-factory-pattern"
      },
      {
        "title": "Adapter Pattern",
        "href": "/interview/design-patterns/v1/adapter-pattern"
      },
      {
        "title": "Bridge Pattern",
        "href": "/interview/design-patterns/v1/bridge-pattern"
      },
      {
        "title": "Builder Pattern in Java – A Delicious Pizza Example",
        "href": "/interview/design-patterns/v1/builder-pattern"
      },
      {
        "title": "Chain of Responsibility Pattern",
        "href": "/interview/design-patterns/v1/chain-of-responsibility-pattern"
      },
      {
        "title": "Command Pattern",
        "href": "/interview/design-patterns/v1/command-pattern"
      },
      {
        "title": "Composite Pattern",
        "href": "/interview/design-patterns/v1/composite-pattern"
      },
      {
        "title": "CQRS (Command Query Responsibility Segregation) — 20 minute lesson (Java-first)",
        "href": "/interview/design-patterns/v1/cqrs-pattern"
      },
      {
        "title": "Decorator Pattern",
        "href": "/interview/design-patterns/v1/decorator-pattern"
      },
      {
        "title": "Dependency Injection",
        "href": "/interview/design-patterns/v1/dependency-injection"
      },
      {
        "title": "Event Sourcing — 20 minute lesson (Java-first)",
        "href": "/interview/design-patterns/v1/event-sourcing-pattern"
      },
      {
        "title": "Facade Pattern",
        "href": "/interview/design-patterns/v1/facade-pattern"
      },
      {
        "title": "Factory Method Pattern in Java – Payment Modes Example",
        "href": "/interview/design-patterns/v1/factory-method-pattern"
      },
      {
        "title": "Flyweight Pattern",
        "href": "/interview/design-patterns/v1/flyweight-pattern"
      },
      {
        "title": "Interpreter Pattern — 20 minute lesson",
        "href": "/interview/design-patterns/v1/interpreter-pattern"
      },
      {
        "title": "Iterator Pattern — 20 minute lesson",
        "href": "/interview/design-patterns/v1/iterator-pattern"
      },
      {
        "title": "Mediator Pattern",
        "href": "/interview/design-patterns/v1/mediator-pattern"
      },
      {
        "title": "Memento Pattern — 20 minute lesson",
        "href": "/interview/design-patterns/v1/memento-pattern"
      },
      {
        "title": "Mock Interview - Applying Patterns",
        "href": "/interview/design-patterns/v1/mock-interview-patterns"
      },
      {
        "title": "Observer Pattern",
        "href": "/interview/design-patterns/v1/observer-pattern"
      },
      {
        "title": "Classification of Design Patterns",
        "href": "/interview/design-patterns/v1/patterns-classification"
      },
      {
        "title": "Prototype Pattern",
        "href": "/interview/design-patterns/v1/prototype-pattern"
      },
      {
        "title": "Proxy Pattern",
        "href": "/interview/design-patterns/v1/proxy-pattern"
      },
      {
        "title": "Repository Pattern — 20 minute lesson",
        "href": "/interview/design-patterns/v1/repository-pattern"
      },
      {
        "title": "Singleton Pattern",
        "href": "/interview/design-patterns/v1/singleton-pattern"
      },
      {
        "title": "State Pattern",
        "href": "/interview/design-patterns/v1/state-pattern"
      },
      {
        "title": "Strategy Pattern in Java: A Step-by-Step Tutorial with Example",
        "href": "/interview/design-patterns/v1/strategy-pattern"
      },
      {
        "title": "Template Method Pattern",
        "href": "/interview/design-patterns/v1/template-method-pattern"
      },
      {
        "title": "Visitor Pattern — 20 minute lesson",
        "href": "/interview/design-patterns/v1/visitor-pattern"
      }
    ]
  },
  {
    "title": "Design Principles",
    "href": "/interview/design-principles/v1",
    "children": [
      {
        "title": "Composition over Inheritance",
        "href": "/interview/design-principles/v1/composition-over-inheritance"
      },
      {
        "title": "Dependency Inversion Principle",
        "href": "/interview/design-principles/v1/dependency-inversion-principle"
      },
      {
        "title": "DRY - Don’t Repeat Yourself",
        "href": "/interview/design-principles/v1/dry-principle"
      },
      {
        "title": "Favor Immutability",
        "href": "/interview/design-principles/v1/favor-immutability"
      },
      {
        "title": "High Cohesion & Low Coupling",
        "href": "/interview/design-principles/v1/high-cohesion-low-coupling"
      },
      {
        "title": "Information Hiding",
        "href": "/interview/design-principles/v1/information-hiding"
      },
      {
        "title": "Interface Segregation Principle",
        "href": "/interview/design-principles/v1/interface-segregation-principle"
      },
      {
        "title": "Introduction to Design Principles",
        "href": "/interview/design-principles/v1/intro-design-principles"
      },
      {
        "title": "KISS - Keep It Simple, Stupid",
        "href": "/interview/design-principles/v1/kiss-principle"
      },
      {
        "title": "Law of Demeter",
        "href": "/interview/design-principles/v1/law-of-demeter"
      },
      {
        "title": "Principle of Least Privilege (Least Authority)",
        "href": "/interview/design-principles/v1/least-privilege"
      },
      {
        "title": "Liskov Substitution Principle",
        "href": "/interview/design-principles/v1/liskov-substitution-principle"
      },
      {
        "title": "Open-Closed Principle",
        "href": "/interview/design-principles/v1/open-closed-principle"
      },
      {
        "title": "POLA and GRASP Principles",
        "href": "/interview/design-principles/v1/pola-grasp-principles"
      },
      {
        "title": "Programming to an Interface, not an Implementation",
        "href": "/interview/design-principles/v1/program-to-interface"
      },
      {
        "title": "Separation of Concerns",
        "href": "/interview/design-principles/v1/separation-of-concerns"
      },
      {
        "title": "Single Responsibility Principle",
        "href": "/interview/design-principles/v1/single-responsibility-principle"
      },
      {
        "title": "YAGNI - You Aren’t Gonna Need It",
        "href": "/interview/design-principles/v1/yagni-principle"
      }
    ]
  },
  {
    "title": "Facing Interviews",
    "href": "/interview/facing-interviews/v1"
  },
  {
    "title": "Computer Science fundamentals",
    "href": "/interview/fundamentals/v1",
    "children": [
      {
        "title": "Ai",
        "href": "/interview/fundamentals/v1/ai/gpu-vs-tpu",
        "children": [
          {
            "title": "GPU vs TPU for AI Workloads",
            "href": "/interview/fundamentals/v1/ai/gpu-vs-tpu"
          },
          {
            "title": "How AI Works - A Layman’s Guide",
            "href": "/interview/fundamentals/v1/ai/how-ai-works"
          },
          {
            "title": "Neural Networks Explained - Structure, Types, and Applications",
            "href": "/interview/fundamentals/v1/ai/neural-networks"
          }
        ]
      },
      {
        "title": "Architecture",
        "href": "/interview/fundamentals/v1/architecture/cpu",
        "children": [
          {
            "title": "How CPUs Work - Instruction Cycle and Pipelines",
            "href": "/interview/fundamentals/v1/architecture/cpu"
          },
          {
            "title": "GPUs & Parallel Computing",
            "href": "/interview/fundamentals/v1/architecture/gpus"
          },
          {
            "title": "Caches & Memory Hierarchy",
            "href": "/interview/fundamentals/v1/architecture/memory-hierarchy"
          },
          {
            "title": "Storage- SSD vs HDD, File Systems",
            "href": "/interview/fundamentals/v1/architecture/storage"
          }
        ]
      },
      {
        "title": "Infra Cloud",
        "href": "/interview/fundamentals/v1/infra-cloud/ai-infra",
        "children": [
          {
            "title": "GPU and AI Infra - Telemetry and Observability",
            "href": "/interview/fundamentals/v1/infra-cloud/ai-infra"
          },
          {
            "title": "CI/CD Pipelines",
            "href": "/interview/fundamentals/v1/infra-cloud/cicd-pipelines"
          },
          {
            "title": "Cloud Fundamentals - AWS / GCP / Azure / OCI",
            "href": "/interview/fundamentals/v1/infra-cloud/cloud-fundamentals"
          },
          {
            "title": "Containerization - Docker & Kubernetes",
            "href": "/interview/fundamentals/v1/infra-cloud/containerization"
          },
          {
            "title": "Distributed Systems - CAP, Consensus",
            "href": "/interview/fundamentals/v1/infra-cloud/distributed-systems-cap-consensus"
          },
          {
            "title": "Microservices Pitfalls and Best Practices",
            "href": "/interview/fundamentals/v1/infra-cloud/microservices"
          },
          {
            "title": "Monitoring and Alerts in Distributed Systems",
            "href": "/interview/fundamentals/v1/infra-cloud/monitoring-alerts"
          },
          {
            "title": "Security in Infrastructure",
            "href": "/interview/fundamentals/v1/infra-cloud/security-infra"
          },
          {
            "title": "IaC with Terraform",
            "href": "/interview/fundamentals/v1/infra-cloud/terraform-iac"
          }
        ]
      },
      {
        "title": "Misc",
        "href": "/interview/fundamentals/v1/misc/cdn-basics",
        "children": [
          {
            "title": "CDN Basics",
            "href": "/interview/fundamentals/v1/misc/cdn-basics"
          },
          {
            "title": "Circuit Breaker Pattern",
            "href": "/interview/fundamentals/v1/misc/circuit_breaker"
          },
          {
            "title": "Common Terms in Infrastructure and System Design",
            "href": "/interview/fundamentals/v1/misc/common_terms"
          },
          {
            "title": "Compression & Encoding (Base64, gzip)",
            "href": "/interview/fundamentals/v1/misc/compression"
          },
          {
            "title": "DNS Deep Dive",
            "href": "/interview/fundamentals/v1/misc/dns"
          },
          {
            "title": "Email Protocols (SMTP, IMAP, POP3)",
            "href": "/interview/fundamentals/v1/misc/email"
          },
          {
            "title": "Messaging Queues and Streaming Technologies",
            "href": "/interview/fundamentals/v1/misc/messaging_queues_streaming"
          },
          {
            "title": "Multipart APIs and File Uploads",
            "href": "/interview/fundamentals/v1/misc/multipart_apis"
          },
          {
            "title": "Real-Time Communication on the Web",
            "href": "/interview/fundamentals/v1/misc/real_time_communication"
          },
          {
            "title": "REST Architecture",
            "href": "/interview/fundamentals/v1/misc/rest_architecture"
          },
          {
            "title": "Video Streaming Technologies",
            "href": "/interview/fundamentals/v1/misc/video_streaming_technology"
          }
        ]
      },
      {
        "title": "Networking",
        "href": "/interview/fundamentals/v1/networking/http-codes",
        "children": [
          {
            "title": "Common HTTP Status Codes",
            "href": "/interview/fundamentals/v1/networking/http-codes"
          },
          {
            "title": "HTTP & HTTPS Basics",
            "href": "/interview/fundamentals/v1/networking/http-https-basics"
          },
          {
            "title": "How the Internet Works",
            "href": "/interview/fundamentals/v1/networking/internet"
          },
          {
            "title": "OSI vs TCP/IP Model",
            "href": "/interview/fundamentals/v1/networking/osi-tcpip"
          },
          {
            "title": "SSL/TLS Basics",
            "href": "/interview/fundamentals/v1/networking/ssl-tls-basics"
          }
        ]
      },
      {
        "title": "Os",
        "href": "/interview/fundamentals/v1/os/concurrency-vs-parallelism",
        "children": [
          {
            "title": "Concurrency vs Parallelism",
            "href": "/interview/fundamentals/v1/os/concurrency-vs-parallelism"
          },
          {
            "title": "Concurrency Control (Locks, Deadlocks, Semaphores)",
            "href": "/interview/fundamentals/v1/os/concurrency"
          },
          {
            "title": "Memory Management (Paging, Segmentation)",
            "href": "/interview/fundamentals/v1/os/memory"
          },
          {
            "title": "Processes vs Threads",
            "href": "/interview/fundamentals/v1/os/processes-vs-threads"
          },
          {
            "title": "CPU Scheduling & Context Switching",
            "href": "/interview/fundamentals/v1/os/scheduling"
          }
        ]
      },
      {
        "title": "Security",
        "href": "/interview/fundamentals/v1/security/auth-vs-authz",
        "children": [
          {
            "title": "👉 Authentication vs Authorization - Key Differences Explained with Examples",
            "href": "/interview/fundamentals/v1/security/auth-vs-authz"
          },
          {
            "title": "Hashing vs Encryption - Key Differences, Examples, and Best Practices",
            "href": "/interview/fundamentals/v1/security/hashing-encryption"
          },
          {
            "title": "Public Key Cryptography (RSA, SSL/TLS)",
            "href": "/interview/fundamentals/v1/security/pki"
          }
        ]
      }
    ]
  },
  {
    "title": "HLD Series Hub",
    "href": "/interview/hld/v1",
    "children": [
      {
        "title": "Database for HLD",
        "href": "/interview/hld/v1/database-for-hld"
      },
      {
        "title": "Scaling to Millions (One-Pager)",
        "href": "/interview/hld/v1/scaling-one-pager"
      },
      {
        "title": "Scaling to millions of users",
        "href": "/interview/hld/v1/scaling-to-millions-users"
      },
      {
        "title": "Soft Skills for HLD Interviews",
        "href": "/interview/hld/v1/soft-skills-hld"
      },
      {
        "title": "Caching",
        "href": "/interview/hld/v1/caching/cdn-caching",
        "children": [
          {
            "title": "CDN Caching",
            "href": "/interview/hld/v1/caching/cdn-caching"
          },
          {
            "title": "TTLs & Eviction Policies",
            "href": "/interview/hld/v1/caching/eviction-policies"
          },
          {
            "title": "Cache Pitfalls — Invalidation & Hot Keys",
            "href": "/interview/hld/v1/caching/pitfalls"
          },
          {
            "title": "Cache Strategies — Cache-aside, Write-through, Write-back",
            "href": "/interview/hld/v1/caching/strategies"
          }
        ]
      },
      {
        "title": "Diagramming",
        "href": "/interview/hld/v1/diagramming/c4_model",
        "children": [
          {
            "title": "What is the C4 Model?",
            "href": "/interview/hld/v1/diagramming/c4_model"
          }
        ]
      },
      {
        "title": "Distributed",
        "href": "/interview/hld/v1/distributed/cap-pacelc",
        "children": [
          {
            "title": "CAP Theorem & PACELC",
            "href": "/interview/hld/v1/distributed/cap-pacelc"
          },
          {
            "title": "Consensus Algorithms — Raft & Paxos",
            "href": "/interview/hld/v1/distributed/consensus"
          },
          {
            "title": "Eventual vs Strong Consistency",
            "href": "/interview/hld/v1/distributed/consistency-tradeoffs"
          },
          {
            "title": "Leader Election, Heartbeats & Failover",
            "href": "/interview/hld/v1/distributed/leader-election"
          },
          {
            "title": "Quorum Reads & Writes",
            "href": "/interview/hld/v1/distributed/quorum"
          }
        ]
      },
      {
        "title": "Faq Problems",
        "href": "/interview/hld/v1/faq-problems/frequently-asked-problems",
        "children": [
          {
            "title": "Frequently Asked HLD Problems",
            "href": "/interview/hld/v1/faq-problems/frequently-asked-problems"
          }
        ]
      },
      {
        "title": "Foundations",
        "href": "/interview/hld/v1/foundations/system-design-mindset",
        "children": [
          {
            "title": "System Design Mindset",
            "href": "/interview/hld/v1/foundations/system-design-mindset"
          },
          {
            "title": "Workload Estimation",
            "href": "/interview/hld/v1/foundations/workload-estimation"
          }
        ]
      },
      {
        "title": "Networking",
        "href": "/interview/hld/v1/networking/apis",
        "children": [
          {
            "title": "APIs — REST vs GraphQL",
            "href": "/interview/hld/v1/networking/apis"
          },
          {
            "title": "CDNs & Edge Computing",
            "href": "/interview/hld/v1/networking/cdns-edge"
          },
          {
            "title": "Load Balancing — L4 vs L7, Algorithms",
            "href": "/interview/hld/v1/networking/load-balancing"
          },
          {
            "title": "Networking Protocols — HTTP, HTTPS, gRPC, WebSockets",
            "href": "/interview/hld/v1/networking/protocols"
          }
        ]
      },
      {
        "title": "Observability",
        "href": "/interview/hld/v1/observability/alerting",
        "children": [
          {
            "title": "Alerting in Distributed Systems",
            "href": "/interview/hld/v1/observability/alerting"
          },
          {
            "title": "Centralized Logging in Distributed Systems",
            "href": "/interview/hld/v1/observability/logging"
          },
          {
            "title": "Monitoring in Distributed Systems",
            "href": "/interview/hld/v1/observability/monitoring"
          },
          {
            "title": "Distributed Tracing in Distributed Systems",
            "href": "/interview/hld/v1/observability/tracing"
          }
        ]
      },
      {
        "title": "Problems",
        "href": "/interview/hld/v1/problems/chat-system",
        "children": [
          {
            "title": "Chat System (WhatsApp / Slack)",
            "href": "/interview/hld/v1/problems/chat-system"
          },
          {
            "title": "E-commerce Checkout (Amazon)",
            "href": "/interview/hld/v1/problems/ecommerce"
          },
          {
            "title": "News Feed (Facebook/Twitter)",
            "href": "/interview/hld/v1/problems/news-feed"
          },
          {
            "title": "Payment System Design",
            "href": "/interview/hld/v1/problems/payment-system"
          },
          {
            "title": "Ride Hailing (Uber)",
            "href": "/interview/hld/v1/problems/ride-hailing"
          },
          {
            "title": "Search System (Google / Elasticsearch)",
            "href": "/interview/hld/v1/problems/search"
          },
          {
            "title": "URL Shortener (TinyURL)",
            "href": "/interview/hld/v1/problems/url-shortener"
          },
          {
            "title": "Video Streaming (YouTube / Netflix)",
            "href": "/interview/hld/v1/problems/video-streaming"
          }
        ]
      },
      {
        "title": "Reliability",
        "href": "/interview/hld/v1/reliability/circuit-breakers",
        "children": [
          {
            "title": "Circuit Breakers, Retries & Timeouts",
            "href": "/interview/hld/v1/reliability/circuit-breakers"
          },
          {
            "title": "Failover Strategies — Active-Passive vs Active-Active",
            "href": "/interview/hld/v1/reliability/failover"
          },
          {
            "title": "Geo-replication & Multi-region",
            "href": "/interview/hld/v1/reliability/geo-replication"
          },
          {
            "title": "Graceful Degradation in Distributed Systems",
            "href": "/interview/hld/v1/reliability/graceful-degradation"
          },
          {
            "title": "Replication — Sync vs Async",
            "href": "/interview/hld/v1/reliability/replication"
          }
        ]
      },
      {
        "title": "Scalability",
        "href": "/interview/hld/v1/scalability/event-driven",
        "children": [
          {
            "title": "Event-driven Architectures",
            "href": "/interview/hld/v1/scalability/event-driven"
          },
          {
            "title": "Microservices vs Monoliths",
            "href": "/interview/hld/v1/scalability/microservices-vs-monoliths"
          },
          {
            "title": "Horizontal vs Vertical Scaling",
            "href": "/interview/hld/v1/scalability/scaling"
          }
        ]
      },
      {
        "title": "Security",
        "href": "/interview/hld/v1/security/authentication-authorization",
        "children": [
          {
            "title": "Authentication vs Authorization",
            "href": "/interview/hld/v1/security/authentication-authorization"
          },
          {
            "title": "DDoS Protection in Distributed Systems",
            "href": "/interview/hld/v1/security/ddos"
          },
          {
            "title": "TLS & Encryption (At Rest vs In Transit)",
            "href": "/interview/hld/v1/security/encryption"
          },
          {
            "title": "Rate Limiting & Throttling",
            "href": "/interview/hld/v1/security/rate-limiting"
          }
        ]
      }
    ]
  },
  {
    "title": "High-Level System Design",
    "href": "/interview/hld-ai/v1",
    "children": [
      {
        "title": "Design an AI Data Center Telemetry System",
        "href": "/interview/hld-ai/v1/ai-telemetry-system"
      },
      {
        "title": "Design an API Rate Limiter",
        "href": "/interview/hld-ai/v1/api-rate-limiter"
      },
      {
        "title": "Capstone - Full HLD Walkthrough with Trade-Offs",
        "href": "/interview/hld-ai/v1/capstone-hld"
      },
      {
        "title": "Design a Content Delivery Network (CDN)",
        "href": "/interview/hld-ai/v1/cdn-design"
      },
      {
        "title": "Integrating HLD with Cloud/Infra",
        "href": "/interview/hld-ai/v1/cloud-infra-integration"
      },
      {
        "title": "Design an Online Collaborative Editor (e.g., Google Docs)",
        "href": "/interview/hld-ai/v1/collaborative-editor"
      },
      {
        "title": "Deep Dive - Consensus Algorithms (Raft/Paxos Basics)",
        "href": "/interview/hld-ai/v1/consensus-algorithms"
      },
      {
        "title": "Design a Distributed Cache System",
        "href": "/interview/hld-ai/v1/distributed-cache"
      },
      {
        "title": "Advanced Topics - Distributed Systems and Trade-Offs",
        "href": "/interview/hld-ai/v1/distributed-systems"
      },
      {
        "title": "Design Dropbox/File Storage System",
        "href": "/interview/hld-ai/v1/dropbox-storage"
      },
      {
        "title": "Design an E-commerce Platform (e.g., Amazon)",
        "href": "/interview/hld-ai/v1/ecommerce-platform"
      },
      {
        "title": "Deep Dive - Event-Driven Architecture",
        "href": "/interview/hld-ai/v1/event-driven-architecture"
      },
      {
        "title": "Functional vs. Non-Functional Requirements",
        "href": "/interview/hld-ai/v1/functional-non-functional"
      },
      {
        "title": "HLD Basics - Components and Diagrams",
        "href": "/interview/hld-ai/v1/hld-basics"
      },
      {
        "title": "Common Pitfalls in HLD",
        "href": "/interview/hld-ai/v1/hld-pitfalls"
      },
      {
        "title": "Design Instagram/Social Media Photo Sharing",
        "href": "/interview/hld-ai/v1/instagram-sharing"
      },
      {
        "title": "Design a Key-Value Store (e.g., Redis)",
        "href": "/interview/hld-ai/v1/key-value-store"
      },
      {
        "title": "Design a Leaderboard/Ranking System",
        "href": "/interview/hld-ai/v1/leaderboard-system"
      },
      {
        "title": "Design a Logging/Monitoring System",
        "href": "/interview/hld-ai/v1/logging-monitoring"
      },
      {
        "title": "Mock HLD Interview - Viewer-Submitted Problem",
        "href": "/interview/hld-ai/v1/mock-hld-interview"
      },
      {
        "title": "Evolving Designs - From Monolith to Microservices",
        "href": "/interview/hld-ai/v1/monolith-to-microservices"
      },
      {
        "title": "Design Netflix/Recommendation System",
        "href": "/interview/hld-ai/v1/netflix-recommendation"
      },
      {
        "title": "Design a News Feed Aggregator",
        "href": "/interview/hld-ai/v1/news-feed-aggregator"
      },
      {
        "title": "Design a Notification System",
        "href": "/interview/hld-ai/v1/notification-system"
      },
      {
        "title": "Design a Pastebin/Code Sharing Service",
        "href": "/interview/hld-ai/v1/pastebin"
      },
      {
        "title": "Design a Payment Gateway",
        "href": "/interview/hld-ai/v1/payment-gateway"
      },
      {
        "title": "Deep Dive - Scaling Databases at 1M Writes/Sec",
        "href": "/interview/hld-ai/v1/scaling-databases"
      },
      {
        "title": "Handling Scale - Sharding, Replication, and Bottlenecks",
        "href": "/interview/hld-ai/v1/scaling-strategies"
      },
      {
        "title": "Design a Search Autocomplete System",
        "href": "/interview/hld-ai/v1/search-autocomplete"
      },
      {
        "title": "Security and Performance in HLD",
        "href": "/interview/hld-ai/v1/security-performance"
      },
      {
        "title": "Design a Social Network Graph (e.g., Friend Recommendations)",
        "href": "/interview/hld-ai/v1/social-network-graph"
      },
      {
        "title": "Design a Ticket Booking System (e.g., BookMyShow)",
        "href": "/interview/hld-ai/v1/ticket-booking"
      },
      {
        "title": "Design a Twitter/X Feed System",
        "href": "/interview/hld-ai/v1/twitter-feed"
      },
      {
        "title": "Design Uber/Ride-Sharing App",
        "href": "/interview/hld-ai/v1/uber-ride-sharing"
      },
      {
        "title": "Design a URL Shortener (e.g., TinyURL)",
        "href": "/interview/hld-ai/v1/url-shortener"
      },
      {
        "title": "Design a Web Crawler/Search Engine Crawler",
        "href": "/interview/hld-ai/v1/web-crawler"
      },
      {
        "title": "Design WhatsApp/Messaging App",
        "href": "/interview/hld-ai/v1/whatsapp-messaging"
      },
      {
        "title": "Design a YouTube/Video Streaming Service",
        "href": "/interview/hld-ai/v1/youtube-streaming"
      }
    ]
  },
  {
    "title": "Interview experiences",
    "href": "/interview/interview-experiences/v1",
    "children": [
      {
        "title": "Karat",
        "href": "/interview/interview-experiences/v1/karat",
        "children": [
          {
            "title": "🚀 How Do You Detect a Cycle in a Linked List?",
            "href": "/interview/interview-experiences/v1/karat/detect_cycle_linked_list"
          },
          {
            "title": "Difference Between Linked List and Array",
            "href": "/interview/interview-experiences/v1/karat/linked_list_vs_array"
          },
          {
            "title": "Lessons Learned from My Karat Interview for Atlassian",
            "href": "/interview/interview-experiences/v1/karat/points-to-keep-in-mind"
          }
        ]
      }
    ]
  },
  {
    "title": "Low-Level System Design",
    "href": "/interview/lld/v1",
    "children": [
      {
        "title": "API Design - RESTful, Idempotency, Versioning",
        "href": "/interview/lld/v1/api-design"
      },
      {
        "title": "Design an ATM Machine",
        "href": "/interview/lld/v1/atm-machine"
      },
      {
        "title": "Design a Cache with Expiry",
        "href": "/interview/lld/v1/cache-with-expiry"
      },
      {
        "title": "Capstone - Combining LLD Components into a System",
        "href": "/interview/lld/v1/capstone-lld"
      },
      {
        "title": "Design a Chess Game",
        "href": "/interview/lld/v1/chess-game"
      },
      {
        "title": "Concurrency Handling - Locks, Threads",
        "href": "/interview/lld/v1/concurrency-handling"
      },
      {
        "title": "Database Design and Indexing",
        "href": "/interview/lld/v1/database-design"
      },
      {
        "title": "Design a Deck of Cards",
        "href": "/interview/lld/v1/deck-of-cards"
      },
      {
        "title": "Design an Elevator System",
        "href": "/interview/lld/v1/elevator-system"
      },
      {
        "title": "Error Handling, Edge Cases, and Resilience",
        "href": "/interview/lld/v1/error-handling"
      },
      {
        "title": "Design a File System",
        "href": "/interview/lld/v1/file-system"
      },
      {
        "title": "Design a Hospital Management System",
        "href": "/interview/lld/v1/hospital-management"
      },
      {
        "title": "LLD Intro - From HLD to Detailed Design",
        "href": "/interview/lld/v1/intro-lld"
      },
      {
        "title": "Design an Inventory Manager",
        "href": "/interview/lld/v1/inventory-manager"
      },
      {
        "title": "Design a Library Management System",
        "href": "/interview/lld/v1/library-management"
      },
      {
        "title": "Integrating LLD with Design Patterns/Principles",
        "href": "/interview/lld/v1/lld-design-patterns"
      },
      {
        "title": "Design a Logger",
        "href": "/interview/lld/v1/logger"
      },
      {
        "title": "Design an LRU Cache",
        "href": "/interview/lld/v1/lru-cache"
      },
      {
        "title": "Design a Matchmaking Engine",
        "href": "/interview/lld/v1/matchmaking-engine"
      },
      {
        "title": "Mock LLD Interview - Live Class Diagram Session",
        "href": "/interview/lld/v1/mock-lld-interview"
      },
      {
        "title": "Design a Movie Ticket Booking System",
        "href": "/interview/lld/v1/movie-ticket-booking"
      },
      {
        "title": "Design a Notification Dispatcher",
        "href": "/interview/lld/v1/notification-dispatcher"
      },
      {
        "title": "Design a Parking Lot System",
        "href": "/interview/lld/v1/parking-lot"
      },
      {
        "title": "Design a Stack Overflow-like Q&A System (Core)",
        "href": "/interview/lld/v1/qa-system"
      },
      {
        "title": "Design a Rate Limiter",
        "href": "/interview/lld/v1/rate-limiter"
      },
      {
        "title": "Design a Restaurant Management System",
        "href": "/interview/lld/v1/restaurant-management"
      },
      {
        "title": "Design Snake and Ladder Game",
        "href": "/interview/lld/v1/snake-ladder"
      },
      {
        "title": "Design a Telemetry Collector",
        "href": "/interview/lld/v1/telemetry-collector"
      },
      {
        "title": "Design a Text Editor (e.g., Notepad)",
        "href": "/interview/lld/v1/text-editor"
      },
      {
        "title": "Building a clean Tic‑Tac‑Toe in Java — a practical LLD walkthrough",
        "href": "/interview/lld/v1/tic-tac-toe"
      },
      {
        "title": "Design a Traffic Light Controller",
        "href": "/interview/lld/v1/traffic-light"
      },
      {
        "title": "Design a URL Parser",
        "href": "/interview/lld/v1/url-parser"
      },
      {
        "title": "Design a Vending Machine",
        "href": "/interview/lld/v1/vending-machine"
      },
      {
        "title": "Uml",
        "href": "/interview/lld/v1/uml/activity_diagrams",
        "children": [
          {
            "title": "What is an Activity Diagram?",
            "href": "/interview/lld/v1/uml/activity_diagrams"
          },
          {
            "title": "Class Diagrams - Structure of Objects, Attributes, Methods",
            "href": "/interview/lld/v1/uml/class_diagrams"
          },
          {
            "title": "Relationships Between Classes in OOP",
            "href": "/interview/lld/v1/uml/class_relationships"
          },
          {
            "title": "What is a Component Diagram?",
            "href": "/interview/lld/v1/uml/component_diagrams"
          },
          {
            "title": "Sequence Diagrams — Object Interactions Over Time",
            "href": "/interview/lld/v1/uml/sequence_diagrams"
          },
          {
            "title": "Use Case Diagrams - Actors and Goals",
            "href": "/interview/lld/v1/uml/use_case_diagrams"
          },
          {
            "title": "What is UML?",
            "href": "/interview/lld/v1/uml/what_is_uml"
          }
        ]
      }
    ]
  },
  {
    "title": "Mock Interview Practice",
    "href": "/interview/mocks/v1",
    "children": [
      {
        "title": "Mock Behavioral Interview",
        "href": "/interview/mocks/v1/behavioral-interview"
      },
      {
        "title": "Mock Coding Interview",
        "href": "/interview/mocks/v1/coding-interview"
      },
      {
        "title": "Capstone - Simulating a Full FAANG Onsite",
        "href": "/interview/mocks/v1/full-onsite"
      },
      {
        "title": "Mock System Design Interview",
        "href": "/interview/mocks/v1/system-design-interview"
      }
    ]
  },
  {
    "title": "Node.js Interview tips Hub",
    "href": "/interview/nodejs/v1",
    "children": [
      {
        "title": "JavaScript Event Loop Explained (2025 Edition)",
        "href": "/interview/nodejs/v1/event-loop"
      },
      {
        "title": "How to Prepare for JavaScript Interviews — Role-Specific Guide",
        "href": "/interview/nodejs/v1/javascript"
      },
      {
        "title": "Node.js Interview Questions & Deep-Dive Topics",
        "href": "/interview/nodejs/v1/node-specific"
      },
      {
        "title": "Javascript",
        "href": "/interview/nodejs/v1/javascript/backend",
        "children": [
          {
            "title": "Backend JavaScript Interview Questions (Node.js Focus)",
            "href": "/interview/nodejs/v1/javascript/backend"
          },
          {
            "title": "Common JavaScript Interview Questions (Frontend + Backend)",
            "href": "/interview/nodejs/v1/javascript/common"
          },
          {
            "title": "Frontend JavaScript Interview Questions",
            "href": "/interview/nodejs/v1/javascript/frontend"
          }
        ]
      }
    ]
  },
  {
    "title": "Object-Oriented Programming & Java Essentials",
    "href": "/interview/oop-java/v1",
    "children": [
      {
        "title": "Collections Framework & Hashing in Java",
        "href": "/interview/oop-java/v1/collections_hashing_java"
      },
      {
        "title": "Exceptions & Error Handling in Java",
        "href": "/interview/oop-java/v1/exceptions_error_handling"
      },
      {
        "title": "Immutability in Java — final, String, and Collections",
        "href": "/interview/oop-java/v1/immutability_java"
      },
      {
        "title": "Essentials",
        "href": "/interview/oop-java/v1/essentials/abstraction-vs-encapsulation",
        "children": [
          {
            "title": "Abstraction vs Encapsulation in OOP",
            "href": "/interview/oop-java/v1/essentials/abstraction-vs-encapsulation"
          },
          {
            "title": "Abstraction in OOP",
            "href": "/interview/oop-java/v1/essentials/abstraction"
          },
          {
            "title": "Encapsulation in OOP",
            "href": "/interview/oop-java/v1/essentials/encapsulation"
          },
          {
            "title": "Inheritance in Object-Oriented Programming",
            "href": "/interview/oop-java/v1/essentials/inheritance"
          },
          {
            "title": "Polymorphism in Object-Oriented Programming",
            "href": "/interview/oop-java/v1/essentials/polymorphism"
          }
        ]
      },
      {
        "title": "Java 8",
        "href": "/interview/oop-java/v1/java-8/lambdas_functional_interfaces",
        "children": [
          {
            "title": "Lambdas & Functional Interfaces in Java",
            "href": "/interview/oop-java/v1/java-8/lambdas_functional_interfaces"
          },
          {
            "title": "Optional in Java",
            "href": "/interview/oop-java/v1/java-8/optional_in_java"
          },
          {
            "title": "Streams API in Java",
            "href": "/interview/oop-java/v1/java-8/streams_api_java"
          }
        ]
      },
      {
        "title": "Locks Synchronization",
        "href": "/interview/oop-java/v1/locks-synchronization/advanced_locking_patterns",
        "children": [
          {
            "title": "Advanced Locking & Patterns in Java",
            "href": "/interview/oop-java/v1/locks-synchronization/advanced_locking_patterns"
          },
          {
            "title": "Explicit Locks in Java — ReentrantLock",
            "href": "/interview/oop-java/v1/locks-synchronization/explicit_locks_reentrantlock"
          },
          {
            "title": "High-Level Abstractions vs Locks in Java",
            "href": "/interview/oop-java/v1/locks-synchronization/high_level_abstractions_vs_locks"
          },
          {
            "title": "Read-Write & Stamped Locks",
            "href": "/interview/oop-java/v1/locks-synchronization/readwrite_stamped_lock"
          },
          {
            "title": "Synchronization Basics in Java",
            "href": "/interview/oop-java/v1/locks-synchronization/synchronization_basics"
          }
        ]
      },
      {
        "title": "Memory Gc",
        "href": "/interview/oop-java/v1/memory-gc/garbage_collection_fundamentals",
        "children": [
          {
            "title": "Garbage Collection Fundamentals in Java",
            "href": "/interview/oop-java/v1/memory-gc/garbage_collection_fundamentals"
          },
          {
            "title": "Advanced GC Topics in Java",
            "href": "/interview/oop-java/v1/memory-gc/gc_advanced_topics"
          },
          {
            "title": "Garbage Collection Algorithms",
            "href": "/interview/oop-java/v1/memory-gc/gc_algorithms"
          },
          {
            "title": "GC Implementations in HotSpot JVM",
            "href": "/interview/oop-java/v1/memory-gc/gc_hotspot"
          },
          {
            "title": "Tuning & Monitoring Garbage Collection in JVM",
            "href": "/interview/oop-java/v1/memory-gc/gc_tuning_monitoring"
          },
          {
            "title": "Java Memory Model Basics",
            "href": "/interview/oop-java/v1/memory-gc/java_memory_model_basics"
          }
        ]
      },
      {
        "title": "Multithreading Concurrency",
        "href": "/interview/oop-java/v1/multithreading-concurrency/java-concurrency-utilities",
        "children": [
          {
            "title": "Concurrency Utilities in Java",
            "href": "/interview/oop-java/v1/multithreading-concurrency/java-concurrency-utilities"
          },
          {
            "title": "Java Multithreading & Concurrency (Part 1) - Thread Basics",
            "href": "/interview/oop-java/v1/multithreading-concurrency/java-thread-basics"
          },
          {
            "title": "Advanced Topics in Java Concurrency",
            "href": "/interview/oop-java/v1/multithreading-concurrency/java_advanced_concurrency"
          },
          {
            "title": "Java Concurrency – Interview & Real-World Scenarios",
            "href": "/interview/oop-java/v1/multithreading-concurrency/java_concurrency_misc"
          },
          {
            "title": "Executor Framework in Java (Expanded)",
            "href": "/interview/oop-java/v1/multithreading-concurrency/java_executor_framework"
          },
          {
            "title": "Synchronization & Thread Safety in Java",
            "href": "/interview/oop-java/v1/multithreading-concurrency/java_synchronization_thread_safety"
          },
          {
            "title": "Java Multithreading & Concurrency — Overview",
            "href": "/interview/oop-java/v1/multithreading-concurrency/overview"
          }
        ]
      },
      {
        "title": "Race Condition",
        "href": "/interview/oop-java/v1/race-condition/advanced-topics-design-patterns-java",
        "children": [
          {
            "title": "Advanced Topics & Design Patterns in Java Concurrency",
            "href": "/interview/oop-java/v1/race-condition/advanced-topics-design-patterns-java"
          },
          {
            "title": "Part 1 — Understanding Race Conditions in Java",
            "href": "/interview/oop-java/v1/race-condition/introduction"
          },
          {
            "title": "Preventing Race Conditions in Java",
            "href": "/interview/oop-java/v1/race-condition/preventing-race-conditions-java"
          }
        ]
      }
    ]
  },
  {
    "title": "Mastering Refactoring",
    "href": "/interview/refactoring/v1",
    "children": [
      {
        "title": "Advanced Refactoring Techniques and Tools",
        "href": "/interview/refactoring/v1/advanced-techniques"
      },
      {
        "title": "Identifying Code Smells",
        "href": "/interview/refactoring/v1/code-smells"
      },
      {
        "title": "Refactoring for Concurrency and Performance",
        "href": "/interview/refactoring/v1/concurrency-performance"
      },
      {
        "title": "Introduction to Refactoring - Goals and Process",
        "href": "/interview/refactoring/v1/intro-refactoring"
      },
      {
        "title": "Refactoring Case Study - Monolith to Microservices",
        "href": "/interview/refactoring/v1/monolith-microservices"
      },
      {
        "title": "Refactoring with Patterns and Principles",
        "href": "/interview/refactoring/v1/patterns-principles"
      },
      {
        "title": "Simplifying Code through Refactoring",
        "href": "/interview/refactoring/v1/simplifying-code"
      }
    ]
  }
];
